/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type HomePage = {
  _id: string
  _type: "homePage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroHeadline?: string
  heroSubheadline?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  heroCtaText?: string
  heroCtaLink?: string
  eventsSectionTitle?: string
  noEventsMessage?: string
  newsletterHeadline?: string
  newsletterBody?: string
  donateHeadline?: string
  donateBody?: string
  donateButtonText?: string
  donateButtonLink?: string
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type PageReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "page"
}

export type SiteSettings = {
  _id: string
  _type: "siteSettings"
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  mainNav?: Array<
    {
      _key: string
    } & PageReference
  >
  newsletterUrl?: string
  socialLinks?: Array<{
    platform?: string
    url?: string
    _key: string
  }>
  socialIconStyle?: "outline" | "filled"
  callToActionText?: string
  callToActionLink?: string
  contactEmail?: string
  contactEmailSubject?: string
}

export type Page = {
  _id: string
  _type: "page"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | PageReference
  | SiteSettings
  | Page
  | Slug
  | Post
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/queries/homePage.ts
// Variable: HOME_PAGE_QUERY
// Query: {  "events": *[_type == "event" && date >= now()] | order(date asc) {    _id,    title,    date,    location,    description,    rsvpLink  },  "settings": *[_type == "siteSettings"][0],  "home": *[_type == "homePage" && _id == "homePage"][0]}
export type HOME_PAGE_QUERY_RESULT = {
  events: Array<never>
  settings: {
    _id: string
    _type: "siteSettings"
    _createdAt: string
    _updatedAt: string
    _rev: string
    siteTitle?: string
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    mainNav?: Array<
      {
        _key: string
      } & PageReference
    >
    newsletterUrl?: string
    socialLinks?: Array<{
      platform?: string
      url?: string
      _key: string
    }>
    socialIconStyle?: "filled" | "outline"
    callToActionText?: string
    callToActionLink?: string
    contactEmail?: string
    contactEmailSubject?: string
  } | null
  home: {
    _id: "homePage"
    _type: "homePage"
    _createdAt: string
    _updatedAt: string
    _rev: string
    heroHeadline?: string
    heroSubheadline?: string
    heroImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    heroCtaText?: string
    heroCtaLink?: string
    eventsSectionTitle?: string
    noEventsMessage?: string
    newsletterHeadline?: string
    newsletterBody?: string
    donateHeadline?: string
    donateBody?: string
    donateButtonText?: string
    donateButtonLink?: string
  } | null
}

// Source: sanity/queries/page.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: {  "page": *[_type == "page" && slug.current == $slug][0],  "settings": *[_type == "siteSettings"][0]}
export type PAGE_BY_SLUG_QUERY_RESULT = {
  page: {
    _id: string
    _type: "page"
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }>
  } | null
  settings: {
    _id: string
    _type: "siteSettings"
    _createdAt: string
    _updatedAt: string
    _rev: string
    siteTitle?: string
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    mainNav?: Array<
      {
        _key: string
      } & PageReference
    >
    newsletterUrl?: string
    socialLinks?: Array<{
      platform?: string
      url?: string
      _key: string
    }>
    socialIconStyle?: "filled" | "outline"
    callToActionText?: string
    callToActionLink?: string
    contactEmail?: string
    contactEmailSubject?: string
  } | null
}

// Source: sanity/queries/settings.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {  siteTitle,  logo,  newsletterUrl,  "navLinks": mainNav[]{_key, ...@->{ title, "slug": slug.current } },  socialLinks,  socialIconStyle,  callToActionText,  callToActionLink,  contactEmail,  contactEmailSubject}
export type SETTINGS_QUERY_RESULT = {
  siteTitle: string | null
  logo: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  newsletterUrl: string | null
  navLinks: Array<{
    _key: string
    title: string | null
    slug: string | null
  }> | null
  socialLinks: Array<{
    platform?: string
    url?: string
    _key: string
  }> | null
  socialIconStyle: "filled" | "outline" | null
  callToActionText: string | null
  callToActionLink: string | null
  contactEmail: string | null
  contactEmailSubject: string | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "events": *[_type == "event" && date >= now()] | order(date asc) {\n    _id,\n    title,\n    date,\n    location,\n    description,\n    rsvpLink\n  },\n  "settings": *[_type == "siteSettings"][0],\n  "home": *[_type == "homePage" && _id == "homePage"][0]\n}': HOME_PAGE_QUERY_RESULT
    '{\n  "page": *[_type == "page" && slug.current == $slug][0],\n  "settings": *[_type == "siteSettings"][0]\n}': PAGE_BY_SLUG_QUERY_RESULT
    '*[_type == "siteSettings"][0] {\n  siteTitle,\n  logo,\n  newsletterUrl,\n  "navLinks": mainNav[]{_key, ...@->{ title, "slug": slug.current } },\n  socialLinks,\n  socialIconStyle,\n  callToActionText,\n  callToActionLink,\n  contactEmail,\n  contactEmailSubject\n}': SETTINGS_QUERY_RESULT
  }
}
